{\rtf1\ansi\ansicpg1252\cocoartf2577
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 hermes                   | 00:55:12 OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k\
hermes                   | 00:55:14 [2021-01-25 23:55:14 +0000] [11] [ERROR] Exception in worker process\
hermes                   | 00:55:14 Traceback (most recent call last):\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker\
hermes                   | 00:55:14     worker.init_process()\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process\
hermes                   | 00:55:14     self.load_wsgi()\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi\
hermes                   | 00:55:14     self.wsgi = self.app.wsgi()\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi\
hermes                   | 00:55:14     self.callable = self.load()\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load\
hermes                   | 00:55:14     return self.load_wsgiapp()\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp\
hermes                   | 00:55:14     return util.import_app(self.app_uri)\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app\
hermes                   | 00:55:14     mod = importlib.import_module(module)\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/importlib/__init__.py", line 127, in import_module\
hermes                   | 00:55:14     return _bootstrap._gcd_import(name[level:], package, level)\
hermes                   | 00:55:14   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import\
hermes                   | 00:55:14   File "<frozen importlib._bootstrap>", line 991, in _find_and_load\
hermes                   | 00:55:14   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked\
hermes                   | 00:55:14   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked\
hermes                   | 00:55:14   File "<frozen importlib._bootstrap_external>", line 783, in exec_module\
hermes                   | 00:55:14   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed\
hermes                   | 00:55:14   File "/workspace/app.py", line 14, in <module>\
hermes                   | 00:55:14     app.config.from_object(os.environ['APP_SETTINGS'])\
hermes                   | 00:55:14   File "/workspace/.heroku/python/lib/python3.8/os.py", line 675, in __getitem__\
hermes                   | 00:55:14     raise KeyError(key) from None\
hermes                   | 00:55:14 KeyError: 'APP_SETTINGS'\
hermes                   | 00:55:14 [2021-01-25 23:55:14 +0000] [11] [INFO] Worker exiting (pid: 11)\
hermes                   | 00:55:14 [2021-01-25 23:55:14 +0000] [1] [INFO] Shutting down: Master\
hermes                   | 00:55:14 [2021-01-25 23:55:14 +0000] [1] [INFO] Reason: Worker failed to boot.}